export const APPLICATION_EXCEPTION_NAME = 'ApplicationBaseException';
export const NOT_FOUND_EXCEPTION_CODE = 'NOT_FOUND';
export const CONFLICT_EXCEPTION_CODE = 'CONFLICT';
export const BAD_REQUEST_EXCEPTION_CODE = 'BAD_REQUEST';
export const UNAUTHORIZED_EXCEPTION_CODE = 'UNAUTHORIZED';
export const FORBIDDEN_EXCEPTION_CODE = 'FORBIDDEN';
export const INTERNAL_SERVER_ERROR_EXCEPTION_CODE = 'INTERNAL_SERVER_ERROR';
