export const PRODUCT_REPOSITORY_TOKEN = Symbol('PRODUCT_REPOSITORY');
export const IMAGE_REPOSITORY_TOKEN = Symbol('IMAGE_REPOSITORY');
export const USER_REPOSITORY_TOKEN = Symbol('USER_REPOSITORY');
export const MEDIA_SERVICE_TOKEN = Symbol('MEDIA_SERVICE');
export const LOGGER_SERVICE_TOKEN = Symbol('LOGGER_SERVICE');
export const SLUGIFY_SERVICE_TOKEN = Symbol('SLUGIFY_SERVICE');
export const AUTH_SERVICE_TOKEN = Symbol('AUTH_SERVICE');
