@baseUrl = http://localhost:8080
@accessToken = token
@jsonType = application/json
@formType = multipart/form-data; boundary=MimeBoundary
@email=tester@example.com
@password=Password123!
@categoryId=11111111-0000-0000-0000-000000000013
@productId=f331cf9a-b671-4008-be27-e3d745c7b73b

### Register
POST {{baseUrl}}/auth/register
Content-Type: {{jsonType}}

{
  "email": "{{email}}",
  "password": "{{password}}",
  "fullName": "Test User"
}

### Login
# @name loginRequest
POST {{baseUrl}}/auth/login
Content-Type: {{jsonType}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Store token
@accessToken={{loginRequest.response.body.access_token}}

### Login
# @name adminLoginRequest
POST {{baseUrl}}/auth/login
Content-Type: {{jsonType}}

{
  "email": "admin@v3x-audio.com",
  "password": "26B9@public.admin"
}

### Store admin token
@accessToken={{adminLoginRequest.response.body.access_token}}

### Get List Products
GET {{baseUrl}}/products

### Create Product
POST {{baseUrl}}/products
Content-Type: {{formType}}
Authorization: Bearer {{accessToken}}

--MimeBoundary
Content-Disposition: form-data; name="name"

Sony WH-1000XM5 Black
--MimeBoundary
Content-Disposition: form-data; name="categoryId"

{{categoryId}}
--MimeBoundary
Content-Disposition: form-data; name="price"

1500
--MimeBoundary
Content-Disposition: form-data; name="stock"

50
--MimeBoundary
Content-Disposition: form-data; name="status"

live
--MimeBoundary
Content-Disposition: form-data; name="description"

Thiết kế mượt mà, ear cup lớn với đệm da mềm, headband mỏng nhẹ, logo Sony rõ ràng, màu đen (Black), nền trắng sạch studio, ánh sáng chuyên nghiệp
--MimeBoundary
Content-Disposition: form-data; name="specs"

{
  "impedance": 32,
  "sensitivity": 105,
  "driverType": "Dynamic",
  "frequencyResponse": {
    "min": 20,
    "max": 20000
  }
}
--MimeBoundary
Content-Disposition: form-data; name="frGraphData"

[[20, 0.5], [100, 2.1], [1000, 0.0]]
--MimeBoundary
Content-Disposition: form-data; name="images"

[
  { "alt": "Sony WH-1000XM5 Black Main View", "isPrimary": true }
]
--MimeBoundary
Content-Disposition: form-data; name="files"; filename="Sony-WH-1000XM5-Black-1.png"
Content-Type: image/png

< ./assets/Sony-WH-1000XM5-Black-1.png
--MimeBoundary--

### Get Product by ID
GET {{baseUrl}}/products/{{productId}}

### Update Product
PATCH {{baseUrl}}/products/{{productId}}
Content-Type: {{formType}}
Authorization: Bearer {{accessToken}}

--MimeBoundary
Content-Disposition: form-data; name="name"

Sony WH-1000XM5 Black (Updated)
--MimeBoundary
Content-Disposition: form-data; name="price"

1450

--MimeBoundary
Content-Disposition: form-data; name="newImages"

[
  { "alt": "Sony WH-1000XM5 Black Side View", "isPrimary": false }
]
--MimeBoundary
Content-Disposition: form-data; name="files"; filename="Sony-WH-1000XM5-Black-2.png"
Content-Type: image/png

< ./assets/Sony-WH-1000XM5-Black-2.png
--MimeBoundary--


### Update Product New Image with primary
PATCH {{baseUrl}}/products/{{productId}}
Content-Type: {{formType}}
Authorization: Bearer {{accessToken}}

--MimeBoundary
Content-Disposition: form-data; name="newImages"

[
  { "alt": "Sony WH-1000XM5 Black Side View (2)", "isPrimary": true }
]
--MimeBoundary
Content-Disposition: form-data; name="files"; filename="Sony-WH-1000XM5-Black-2.png"
Content-Type: image/png

< ./assets/Sony-WH-1000XM5-Black-2.png
--MimeBoundary--

### Update Product with two primary (should fail).
PATCH {{baseUrl}}/products/{{productId}}
Content-Type: {{formType}}
Authorization: Bearer {{accessToken}}

--MimeBoundary
Content-Disposition: form-data; name="keepImages"

[
  { "id": "3f782ae6-8968-4c87-aeb5-85c37a1e1c7f", "isPrimary": true }
]
--MimeBoundary
Content-Disposition: form-data; name="newImages"

[
  { "alt": "Sony WH-1000XM5 Black Side View", "isPrimary": true }
]
--MimeBoundary
Content-Disposition: form-data; name="files"; filename="Sony-WH-1000XM5-Black-2.png"
Content-Type: image/png

< ./assets/Sony-WH-1000XM5-Black-2.png
--MimeBoundary--

### Update Product specify old image is primary (should success).
PATCH {{baseUrl}}/products/{{productId}}
Content-Type: {{formType}}
Authorization: Bearer {{accessToken}}

--MimeBoundary
Content-Disposition: form-data; name="keepImages"

[
  { "id": "7855fba6-9925-44cc-9618-1c26da24af63", "isPrimary": true }
]
--MimeBoundary
Content-Disposition: form-data; name="newImages"

[
  { "alt": "Sony WH-1000XM5 Black Side View (3)", "isPrimary": false }
]
--MimeBoundary
Content-Disposition: form-data; name="files"; filename="Sony-WH-1000XM5-Black-2.png"
Content-Type: image/png

< ./assets/Sony-WH-1000XM5-Black-2.png
--MimeBoundary--