@baseUrl = http://localhost:8080
@accessToken = token
@jsonType = application/json
@formType = multipart/form-data; boundary=MimeBoundary
@email=tester@example.com
@password=Password123!
@categoryId=00000000-0000-0000-0000-000000000001

### Register
POST {{baseUrl}}/auth/register
Content-Type: {{jsonType}}

{
  "email": "{{email}}",
  "password": "{{password}}",
  "fullName": "Test User"
}

### Login
# @name loginRequest
POST {{baseUrl}}/auth/login
Content-Type: {{jsonType}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Store token
@accessToken={{loginRequest.response.body.access_token}}

### Login
# @name adminLoginRequest
POST {{baseUrl}}/auth/login
Content-Type: {{jsonType}}

{
  "email": "admin@v3x-audio.com",
  "password": "26B9@public.admin"
}

### Store admin token
@accessToken={{adminLoginRequest.response.body.access_token}}

### Create Product
POST {{baseUrl}}/products
Content-Type: {{formType}}
Authorization: Bearer {{accessToken}}

--MimeBoundary
Content-Disposition: form-data; name="name"

Sony WH-1000XM5 Black
--MimeBoundary
Content-Disposition: form-data; name="categoryId"

{{categoryId}}
--MimeBoundary
Content-Disposition: form-data; name="price"

1500
--MimeBoundary
Content-Disposition: form-data; name="stock"

50
--MimeBoundary
Content-Disposition: form-data; name="description"

Thiết kế mượt mà, ear cup lớn với đệm da mềm, headband mỏng nhẹ, logo Sony rõ ràng, màu đen (Black), nền trắng sạch studio, ánh sáng chuyên nghiệp
--MimeBoundary
Content-Disposition: form-data; name="specs"

{
  "impedance": 32,
  "sensitivity": 105,
  "driverType": "Dynamic",
  "frequencyResponse": {
    "min": 20,
    "max": 20000
  }
}
--MimeBoundary
Content-Disposition: form-data; name="frGraphData"

[[20, 0.5], [100, 2.1], [1000, 0.0]]
--MimeBoundary
Content-Disposition: form-data; name="images"

[
  { "isPrimary": true }
]
--MimeBoundary
Content-Disposition: form-data; name="files"; filename="Sony-WH-1000XM5-Black-1.jpg"
Content-Type: image/jpg

< ./assets/Sony-WH-1000XM5-Black-1.jpg
--MimeBoundary--

### Get List Products
GET {{baseUrl}}/products